/**
 * OpenClaw Runbooks
 * Predefined incident-response workflow definitions.
 * Each runbook maps directly to valid Capability Registry entries.
 */

export const RUNBOOKS = [
  {
    id: 'runbook_gateway_health',
    name: 'Check Gateway Health',
    description: 'Verify gateway is online and capture a system status snapshot.',
    category: 'monitoring',
    steps: [
      {
        stepId: 'check_status',
        capabilityId: 'system.status',
        entityScope: 'vcm',
        riskLevel: 'low',
        params: {},
        dependsOn: [],
        onFailure: 'STOP',
        timeoutMs: 5000,
      },
    ],
  },
  {
    id: 'runbook_fetch_logs_sessions',
    name: 'Fetch Logs + Sessions',
    description: 'Pull recent error logs then enumerate active browser sessions for incident triage.',
    category: 'monitoring',
    steps: [
      {
        stepId: 'fetch_error_logs',
        capabilityId: 'logs.fetch',
        entityScope: 'gfm_admin',
        riskLevel: 'low',
        params: { limit: 100, level: 'error' },
        dependsOn: [],
        onFailure: 'CONTINUE',
        timeoutMs: 6000,
      },
      {
        stepId: 'list_sessions',
        capabilityId: 'session.list',
        entityScope: 'gfm_admin',
        riskLevel: 'medium',
        params: {},
        dependsOn: ['fetch_error_logs'],
        onFailure: 'STOP',
        timeoutMs: 5000,
      },
    ],
  },
  {
    id: 'runbook_full_triage',
    name: 'Full Incident Triage',
    description: 'Status check → error logs → warn logs → active sessions. Full read-only triage sequence.',
    category: 'monitoring',
    steps: [
      {
        stepId: 'status_check',
        capabilityId: 'system.status',
        entityScope: 'vcm',
        riskLevel: 'low',
        params: {},
        dependsOn: [],
        onFailure: 'CONTINUE',
        timeoutMs: 5000,
      },
      {
        stepId: 'error_logs',
        capabilityId: 'logs.fetch',
        entityScope: 'gfm_admin',
        riskLevel: 'low',
        params: { limit: 200, level: 'error' },
        dependsOn: ['status_check'],
        onFailure: 'CONTINUE',
        timeoutMs: 8000,
      },
      {
        stepId: 'warn_logs',
        capabilityId: 'logs.fetch',
        entityScope: 'gfm_admin',
        riskLevel: 'low',
        params: { limit: 100, level: 'warn' },
        dependsOn: ['status_check'],
        onFailure: 'CONTINUE',
        timeoutMs: 6000,
      },
      {
        stepId: 'active_sessions',
        capabilityId: 'session.list',
        entityScope: 'gfm_admin',
        riskLevel: 'medium',
        params: {},
        dependsOn: ['error_logs', 'warn_logs'],
        onFailure: 'STOP',
        timeoutMs: 5000,
      },
    ],
  },
  {
    id: 'runbook_log_sweep',
    name: 'Log Level Sweep',
    description: 'Fetch debug, info, warn, and error logs in sequence for a comprehensive log sweep.',
    category: 'data',
    steps: [
      {
        stepId: 'debug_logs',
        capabilityId: 'logs.fetch',
        entityScope: 'vcm',
        riskLevel: 'low',
        params: { limit: 50, level: 'debug' },
        dependsOn: [],
        onFailure: 'CONTINUE',
        timeoutMs: 5000,
      },
      {
        stepId: 'info_logs',
        capabilityId: 'logs.fetch',
        entityScope: 'vcm',
        riskLevel: 'low',
        params: { limit: 50, level: 'info' },
        dependsOn: [],
        onFailure: 'CONTINUE',
        timeoutMs: 5000,
      },
      {
        stepId: 'warn_logs',
        capabilityId: 'logs.fetch',
        entityScope: 'vcm',
        riskLevel: 'low',
        params: { limit: 50, level: 'warn' },
        dependsOn: [],
        onFailure: 'CONTINUE',
        timeoutMs: 5000,
      },
      {
        stepId: 'error_logs',
        capabilityId: 'logs.fetch',
        entityScope: 'vcm',
        riskLevel: 'low',
        params: { limit: 50, level: 'error' },
        dependsOn: [],
        onFailure: 'CONTINUE',
        timeoutMs: 5000,
      },
    ],
  },
  {
    id: 'runbook_browser_session_open',
    name: 'Open Browser Session',
    description: 'Open a new headless browser session and enumerate any existing sessions.',
    category: 'browser',
    steps: [
      {
        stepId: 'pre_session_list',
        capabilityId: 'session.list',
        entityScope: 'gfm_admin',
        riskLevel: 'medium',
        params: {},
        dependsOn: [],
        onFailure: 'CONTINUE',
        timeoutMs: 5000,
      },
      {
        stepId: 'open_session',
        capabilityId: 'browser.open',
        entityScope: 'gfm_admin',
        riskLevel: 'medium',
        params: { url: 'https://', headless: true },
        dependsOn: ['pre_session_list'],
        onFailure: 'STOP',
        timeoutMs: 10000,
      },
    ],
  },
];

export const CATEGORY_COLORS = {
  monitoring: 'text-blue-400 border-blue-400/30 bg-blue-400/5',
  data:       'text-purple-400 border-purple-400/30 bg-purple-400/5',
  browser:    'text-amber-500 border-amber-500/30 bg-amber-500/5',
};