import React, { useState } from 'react';
import { AlertTriangle, Plus, CheckCircle2, Loader2 } from 'lucide-react';
import { base44 } from '@/api/base44Client';

const PRIORITY_COLOR = {
  CRITICAL: 'text-destructive',
  HIGH: 'text-amber-400',
  MEDIUM: 'text-primary',
  LOW: 'text-slate-400',
};

function buildDraftContent(doc) {
  return `# ${doc.title}

> **Status:** DRAFT — Pending operator review and approval
> **Domain:** ${doc.domain}
> **Priority:** ${doc.priority}
> **File Path:** ${doc.path}

## Overview

This document covers ${doc.title} for the Veridan Core knowledge vault.

## Purpose

[Operator to complete — describe the purpose and scope of this document]

## Key Content Areas

- [Area 1]
- [Area 2]
- [Area 3]

## References

- Veridan Core Governance Charter
- Relevant SOPs

---

*Generated by Veridan Vault Agent v1 · DRAFT — Requires operator review and approval before vault write*
*executionStatus: NOT_EXECUTED · dispatchStatus: NOT_DISPATCHED · openclawCall: NOT_SENT*
`;
}

export default function MissingDocRecommendations({ missingDocs, onDraftCreated }) {
  const [creating, setCreating] = useState({});
  const [created, setCreated] = useState({});

  const handleCreateDraft = async (doc) => {
    const key = doc.path;
    setCreating(prev => ({ ...prev, [key]: true }));
    try {
      const draftId = `VVA-${Date.now().toString(36).toUpperCase()}`;
      const filename = doc.path.split('/').pop();
      const targetFolder = doc.path.split('/').slice(0, -1).join('/');

      await base44.entities.VeridanObsidianDraft.create({
        draftId,
        source: 'MANUAL_LOCAL_DRAFT',
        title: doc.title,
        filename,
        category: doc.domain,
        targetFolder,
        content: buildDraftContent(doc),
        draftType: 'MANUAL_MARKDOWN',
        riskLevel: 'LOW',
        approvalStatus: 'PENDING_REVIEW',
        approvalState: 'PENDING_REVIEW',
        executionStatus: 'NOT_EXECUTED',
        dispatchStatus: 'NOT_DISPATCHED',
        openclawCall: 'NOT_SENT',
        filesystemWrite: 'DISABLED',
        apiMode: 'NO_API_LOCAL_ONLY',
      });

      setCreated(prev => ({ ...prev, [key]: true }));
      if (onDraftCreated) onDraftCreated();
    } catch (e) {
      console.error('Draft creation failed:', e);
    }
    setCreating(prev => ({ ...prev, [key]: false }));
  };

  if (!missingDocs.length) {
    return (
      <div className="border border-primary/30 bg-primary/5 rounded-sm p-6 text-center text-[9px] font-mono text-primary">
        ✓ All expected documents have drafts or are written to vault.
      </div>
    );
  }

  const critical = missingDocs.filter(d => d.priority === 'CRITICAL');
  const others = missingDocs.filter(d => d.priority !== 'CRITICAL');

  return (
    <div className="border border-border/40 bg-card rounded-sm overflow-hidden">
      <div className="flex items-center justify-between gap-2 px-4 py-2.5 border-b border-border/30 bg-card/80">
        <span className="text-[9px] font-bold uppercase tracking-widest text-slate-300">Missing Document Recommendations</span>
        <div className="flex items-center gap-2 text-[7px] font-mono">
          {critical.length > 0 && <span className="text-destructive font-bold">{critical.length} CRITICAL</span>}
          <span className="text-slate-500">{missingDocs.length} total missing</span>
        </div>
      </div>

      {/* Safety note */}
      <div className="flex items-start gap-2 px-4 py-2 bg-amber-500/5 border-b border-amber-500/20">
        <AlertTriangle className="w-3 h-3 text-amber-500 shrink-0 mt-0.5" />
        <span className="text-[7px] font-mono text-amber-400">
          "Queue Draft" creates a PENDING_REVIEW record in VeridanObsidianDraft. No file is written to Obsidian.
          The draft enters the existing approval → write workflow at /obsidian-draft-review.
        </span>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-[7px] font-mono">
          <thead>
            <tr className="border-b border-border/30 bg-card/80">
              {['Title', 'Domain', 'Why It Matters', 'Priority', 'Suggested Path', 'Action'].map(h => (
                <th key={h} className="text-left px-3 py-2 text-slate-500 uppercase font-bold whitespace-nowrap">{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {[...critical, ...others].map((doc, i) => {
              const isCreating = creating[doc.path];
              const isCreated = created[doc.path];
              return (
                <tr key={i} className="border-b border-border/10 hover:bg-card/40">
                  <td className="px-3 py-2 text-slate-200 font-bold whitespace-nowrap">{doc.title}</td>
                  <td className="px-3 py-2 text-slate-400">{doc.domain}</td>
                  <td className="px-3 py-2 text-slate-500 max-w-[200px]">{doc.reason || `Required ${doc.domain} reference`}</td>
                  <td className={`px-3 py-2 font-bold ${PRIORITY_COLOR[doc.priority]}`}>{doc.priority}</td>
                  <td className="px-3 py-2 text-slate-500 max-w-[180px] truncate">{doc.path}</td>
                  <td className="px-3 py-2">
                    {isCreated ? (
                      <span className="flex items-center gap-1 text-primary font-bold">
                        <CheckCircle2 className="w-2.5 h-2.5" /> Queued
                      </span>
                    ) : (
                      <button
                        type="button"
                        onClick={() => handleCreateDraft(doc)}
                        disabled={isCreating}
                        className="flex items-center gap-1 px-2 py-1 border border-primary/40 text-primary bg-primary/10 hover:bg-primary/20 disabled:opacity-50 rounded-sm transition-colors whitespace-nowrap font-bold"
                      >
                        {isCreating
                          ? <><Loader2 className="w-2.5 h-2.5 animate-spin" /> Queuing…</>
                          : <><Plus className="w-2.5 h-2.5" /> Queue Draft</>
                        }
                      </button>
                    )}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}